name: Message Class
author: [Jason Beaudoin, ColdFireDesigns.com]
category: Interface
tags: [animation, message, input, output]
#docs: http://www.coldfiredesigns.com/2010/?p=1
#demo: http://www.coldfiredesigns.com/2010/?p=1