name: Message Class
author: ColdFireDesigns
current: 2.1
category: Interface
tags: [animation, message, input, output]
docs: http://www.coldfiredesigns.com/2010/?p=1
demo: http://www.coldfiredesigns.com/2010/?p=1

copywright: "Jason Beaudoin"
licence: MIT
web: "[coldfiredesigns.com/2010](http://www.coldfiredesigns.com/2010/)"
description: Mootools Message Class